// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbandk/testpb/proto_3_presence.proto

package pbandk.testpb;

public final class Proto3Presence {
  private Proto3Presence() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code pbandk.testpb.Proto3PresenceEnum}
   */
  public enum Proto3PresenceEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PROTO3_PRESENCE_ENUM_UNSPECIFIED = 0;</code>
     */
    PROTO3_PRESENCE_ENUM_UNSPECIFIED(0),
    /**
     * <code>PROTO3_PRESENCE_ENUM_SPECIFIED = 1;</code>
     */
    PROTO3_PRESENCE_ENUM_SPECIFIED(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PROTO3_PRESENCE_ENUM_UNSPECIFIED = 0;</code>
     */
    public static final int PROTO3_PRESENCE_ENUM_UNSPECIFIED_VALUE = 0;
    /**
     * <code>PROTO3_PRESENCE_ENUM_SPECIFIED = 1;</code>
     */
    public static final int PROTO3_PRESENCE_ENUM_SPECIFIED_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Proto3PresenceEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Proto3PresenceEnum forNumber(int value) {
      switch (value) {
        case 0: return PROTO3_PRESENCE_ENUM_UNSPECIFIED;
        case 1: return PROTO3_PRESENCE_ENUM_SPECIFIED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Proto3PresenceEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Proto3PresenceEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Proto3PresenceEnum>() {
            public Proto3PresenceEnum findValueByNumber(int number) {
              return Proto3PresenceEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return pbandk.testpb.Proto3Presence.getDescriptor().getEnumTypes().get(0);
    }

    private static final Proto3PresenceEnum[] VALUES = values();

    public static Proto3PresenceEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Proto3PresenceEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:pbandk.testpb.Proto3PresenceEnum)
  }

  public interface Proto3PresenceMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbandk.testpb.Proto3PresenceMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 int = 1;</code>
     * @return The int.
     */
    int getInt();
  }
  /**
   * Protobuf type {@code pbandk.testpb.Proto3PresenceMessage}
   */
  public static final class Proto3PresenceMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pbandk.testpb.Proto3PresenceMessage)
      Proto3PresenceMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Proto3PresenceMessage.newBuilder() to construct.
    private Proto3PresenceMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Proto3PresenceMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Proto3PresenceMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Proto3PresenceMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              int_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pbandk.testpb.Proto3Presence.internal_static_pbandk_testpb_Proto3PresenceMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pbandk.testpb.Proto3Presence.internal_static_pbandk_testpb_Proto3PresenceMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pbandk.testpb.Proto3Presence.Proto3PresenceMessage.class, pbandk.testpb.Proto3Presence.Proto3PresenceMessage.Builder.class);
    }

    public static final int INT_FIELD_NUMBER = 1;
    private int int_;
    /**
     * <code>int32 int = 1;</code>
     * @return The int.
     */
    @java.lang.Override
    public int getInt() {
      return int_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (int_ != 0) {
        output.writeInt32(1, int_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (int_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, int_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pbandk.testpb.Proto3Presence.Proto3PresenceMessage)) {
        return super.equals(obj);
      }
      pbandk.testpb.Proto3Presence.Proto3PresenceMessage other = (pbandk.testpb.Proto3Presence.Proto3PresenceMessage) obj;

      if (getInt()
          != other.getInt()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INT_FIELD_NUMBER;
      hash = (53 * hash) + getInt();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pbandk.testpb.Proto3Presence.Proto3PresenceMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pbandk.testpb.Proto3Presence.Proto3PresenceMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pbandk.testpb.Proto3PresenceMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pbandk.testpb.Proto3PresenceMessage)
        pbandk.testpb.Proto3Presence.Proto3PresenceMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pbandk.testpb.Proto3Presence.internal_static_pbandk_testpb_Proto3PresenceMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pbandk.testpb.Proto3Presence.internal_static_pbandk_testpb_Proto3PresenceMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pbandk.testpb.Proto3Presence.Proto3PresenceMessage.class, pbandk.testpb.Proto3Presence.Proto3PresenceMessage.Builder.class);
      }

      // Construct using pbandk.testpb.Proto3Presence.Proto3PresenceMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        int_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pbandk.testpb.Proto3Presence.internal_static_pbandk_testpb_Proto3PresenceMessage_descriptor;
      }

      @java.lang.Override
      public pbandk.testpb.Proto3Presence.Proto3PresenceMessage getDefaultInstanceForType() {
        return pbandk.testpb.Proto3Presence.Proto3PresenceMessage.getDefaultInstance();
      }

      @java.lang.Override
      public pbandk.testpb.Proto3Presence.Proto3PresenceMessage build() {
        pbandk.testpb.Proto3Presence.Proto3PresenceMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pbandk.testpb.Proto3Presence.Proto3PresenceMessage buildPartial() {
        pbandk.testpb.Proto3Presence.Proto3PresenceMessage result = new pbandk.testpb.Proto3Presence.Proto3PresenceMessage(this);
        result.int_ = int_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pbandk.testpb.Proto3Presence.Proto3PresenceMessage) {
          return mergeFrom((pbandk.testpb.Proto3Presence.Proto3PresenceMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pbandk.testpb.Proto3Presence.Proto3PresenceMessage other) {
        if (other == pbandk.testpb.Proto3Presence.Proto3PresenceMessage.getDefaultInstance()) return this;
        if (other.getInt() != 0) {
          setInt(other.getInt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pbandk.testpb.Proto3Presence.Proto3PresenceMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pbandk.testpb.Proto3Presence.Proto3PresenceMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int int_ ;
      /**
       * <code>int32 int = 1;</code>
       * @return The int.
       */
      @java.lang.Override
      public int getInt() {
        return int_;
      }
      /**
       * <code>int32 int = 1;</code>
       * @param value The int to set.
       * @return This builder for chaining.
       */
      public Builder setInt(int value) {
        
        int_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 int = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInt() {
        
        int_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pbandk.testpb.Proto3PresenceMessage)
    }

    // @@protoc_insertion_point(class_scope:pbandk.testpb.Proto3PresenceMessage)
    private static final pbandk.testpb.Proto3Presence.Proto3PresenceMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbandk.testpb.Proto3Presence.Proto3PresenceMessage();
    }

    public static pbandk.testpb.Proto3Presence.Proto3PresenceMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Proto3PresenceMessage>
        PARSER = new com.google.protobuf.AbstractParser<Proto3PresenceMessage>() {
      @java.lang.Override
      public Proto3PresenceMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Proto3PresenceMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Proto3PresenceMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Proto3PresenceMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pbandk.testpb.Proto3Presence.Proto3PresenceMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Proto3PresenceMainOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbandk.testpb.Proto3PresenceMain)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .pbandk.testpb.Proto3PresenceMessage optional_message = 1;</code>
     * @return Whether the optionalMessage field is set.
     */
    boolean hasOptionalMessage();
    /**
     * <code>optional .pbandk.testpb.Proto3PresenceMessage optional_message = 1;</code>
     * @return The optionalMessage.
     */
    pbandk.testpb.Proto3Presence.Proto3PresenceMessage getOptionalMessage();
    /**
     * <code>optional .pbandk.testpb.Proto3PresenceMessage optional_message = 1;</code>
     */
    pbandk.testpb.Proto3Presence.Proto3PresenceMessageOrBuilder getOptionalMessageOrBuilder();

    /**
     * <code>.pbandk.testpb.Proto3PresenceMessage message = 2;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>.pbandk.testpb.Proto3PresenceMessage message = 2;</code>
     * @return The message.
     */
    pbandk.testpb.Proto3Presence.Proto3PresenceMessage getMessage();
    /**
     * <code>.pbandk.testpb.Proto3PresenceMessage message = 2;</code>
     */
    pbandk.testpb.Proto3Presence.Proto3PresenceMessageOrBuilder getMessageOrBuilder();

    /**
     * <code>optional string optional_string = 3;</code>
     * @return Whether the optionalString field is set.
     */
    boolean hasOptionalString();
    /**
     * <code>optional string optional_string = 3;</code>
     * @return The optionalString.
     */
    java.lang.String getOptionalString();
    /**
     * <code>optional string optional_string = 3;</code>
     * @return The bytes for optionalString.
     */
    com.google.protobuf.ByteString
        getOptionalStringBytes();

    /**
     * <code>string string = 4;</code>
     * @return The string.
     */
    java.lang.String getString();
    /**
     * <code>string string = 4;</code>
     * @return The bytes for string.
     */
    com.google.protobuf.ByteString
        getStringBytes();

    /**
     * <code>optional int32 optional_int = 5;</code>
     * @return Whether the optionalInt field is set.
     */
    boolean hasOptionalInt();
    /**
     * <code>optional int32 optional_int = 5;</code>
     * @return The optionalInt.
     */
    int getOptionalInt();

    /**
     * <code>int32 int = 6;</code>
     * @return The int.
     */
    int getInt();

    /**
     * <code>optional .pbandk.testpb.Proto3PresenceEnum optional_enum = 7;</code>
     * @return Whether the optionalEnum field is set.
     */
    boolean hasOptionalEnum();
    /**
     * <code>optional .pbandk.testpb.Proto3PresenceEnum optional_enum = 7;</code>
     * @return The enum numeric value on the wire for optionalEnum.
     */
    int getOptionalEnumValue();
    /**
     * <code>optional .pbandk.testpb.Proto3PresenceEnum optional_enum = 7;</code>
     * @return The optionalEnum.
     */
    pbandk.testpb.Proto3Presence.Proto3PresenceEnum getOptionalEnum();

    /**
     * <code>.pbandk.testpb.Proto3PresenceEnum enum = 8;</code>
     * @return The enum numeric value on the wire for enum.
     */
    int getEnumValue();
    /**
     * <code>.pbandk.testpb.Proto3PresenceEnum enum = 8;</code>
     * @return The enum.
     */
    pbandk.testpb.Proto3Presence.Proto3PresenceEnum getEnum();

    /**
     * <code>string one_of_string = 9;</code>
     * @return Whether the oneOfString field is set.
     */
    boolean hasOneOfString();
    /**
     * <code>string one_of_string = 9;</code>
     * @return The oneOfString.
     */
    java.lang.String getOneOfString();
    /**
     * <code>string one_of_string = 9;</code>
     * @return The bytes for oneOfString.
     */
    com.google.protobuf.ByteString
        getOneOfStringBytes();

    /**
     * <code>int32 one_of_int = 10;</code>
     * @return Whether the oneOfInt field is set.
     */
    boolean hasOneOfInt();
    /**
     * <code>int32 one_of_int = 10;</code>
     * @return The oneOfInt.
     */
    int getOneOfInt();

    public pbandk.testpb.Proto3Presence.Proto3PresenceMain.OneOfCase getOneOfCase();
  }
  /**
   * Protobuf type {@code pbandk.testpb.Proto3PresenceMain}
   */
  public static final class Proto3PresenceMain extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pbandk.testpb.Proto3PresenceMain)
      Proto3PresenceMainOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Proto3PresenceMain.newBuilder() to construct.
    private Proto3PresenceMain(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Proto3PresenceMain() {
      optionalString_ = "";
      string_ = "";
      optionalEnum_ = 0;
      enum_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Proto3PresenceMain();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Proto3PresenceMain(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              pbandk.testpb.Proto3Presence.Proto3PresenceMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = optionalMessage_.toBuilder();
              }
              optionalMessage_ = input.readMessage(pbandk.testpb.Proto3Presence.Proto3PresenceMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(optionalMessage_);
                optionalMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              pbandk.testpb.Proto3Presence.Proto3PresenceMessage.Builder subBuilder = null;
              if (message_ != null) {
                subBuilder = message_.toBuilder();
              }
              message_ = input.readMessage(pbandk.testpb.Proto3Presence.Proto3PresenceMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(message_);
                message_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              optionalString_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              string_ = s;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000004;
              optionalInt_ = input.readInt32();
              break;
            }
            case 48: {

              int_ = input.readInt32();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              bitField0_ |= 0x00000008;
              optionalEnum_ = rawValue;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              enum_ = rawValue;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              oneOfCase_ = 9;
              oneOf_ = s;
              break;
            }
            case 80: {
              oneOf_ = input.readInt32();
              oneOfCase_ = 10;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pbandk.testpb.Proto3Presence.internal_static_pbandk_testpb_Proto3PresenceMain_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pbandk.testpb.Proto3Presence.internal_static_pbandk_testpb_Proto3PresenceMain_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pbandk.testpb.Proto3Presence.Proto3PresenceMain.class, pbandk.testpb.Proto3Presence.Proto3PresenceMain.Builder.class);
    }

    private int bitField0_;
    private int oneOfCase_ = 0;
    private java.lang.Object oneOf_;
    public enum OneOfCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      ONE_OF_STRING(9),
      ONE_OF_INT(10),
      ONEOF_NOT_SET(0);
      private final int value;
      private OneOfCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static OneOfCase valueOf(int value) {
        return forNumber(value);
      }

      public static OneOfCase forNumber(int value) {
        switch (value) {
          case 9: return ONE_OF_STRING;
          case 10: return ONE_OF_INT;
          case 0: return ONEOF_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public OneOfCase
    getOneOfCase() {
      return OneOfCase.forNumber(
          oneOfCase_);
    }

    public static final int OPTIONAL_MESSAGE_FIELD_NUMBER = 1;
    private pbandk.testpb.Proto3Presence.Proto3PresenceMessage optionalMessage_;
    /**
     * <code>optional .pbandk.testpb.Proto3PresenceMessage optional_message = 1;</code>
     * @return Whether the optionalMessage field is set.
     */
    @java.lang.Override
    public boolean hasOptionalMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .pbandk.testpb.Proto3PresenceMessage optional_message = 1;</code>
     * @return The optionalMessage.
     */
    @java.lang.Override
    public pbandk.testpb.Proto3Presence.Proto3PresenceMessage getOptionalMessage() {
      return optionalMessage_ == null ? pbandk.testpb.Proto3Presence.Proto3PresenceMessage.getDefaultInstance() : optionalMessage_;
    }
    /**
     * <code>optional .pbandk.testpb.Proto3PresenceMessage optional_message = 1;</code>
     */
    @java.lang.Override
    public pbandk.testpb.Proto3Presence.Proto3PresenceMessageOrBuilder getOptionalMessageOrBuilder() {
      return optionalMessage_ == null ? pbandk.testpb.Proto3Presence.Proto3PresenceMessage.getDefaultInstance() : optionalMessage_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private pbandk.testpb.Proto3Presence.Proto3PresenceMessage message_;
    /**
     * <code>.pbandk.testpb.Proto3PresenceMessage message = 2;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return message_ != null;
    }
    /**
     * <code>.pbandk.testpb.Proto3PresenceMessage message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public pbandk.testpb.Proto3Presence.Proto3PresenceMessage getMessage() {
      return message_ == null ? pbandk.testpb.Proto3Presence.Proto3PresenceMessage.getDefaultInstance() : message_;
    }
    /**
     * <code>.pbandk.testpb.Proto3PresenceMessage message = 2;</code>
     */
    @java.lang.Override
    public pbandk.testpb.Proto3Presence.Proto3PresenceMessageOrBuilder getMessageOrBuilder() {
      return getMessage();
    }

    public static final int OPTIONAL_STRING_FIELD_NUMBER = 3;
    private volatile java.lang.Object optionalString_;
    /**
     * <code>optional string optional_string = 3;</code>
     * @return Whether the optionalString field is set.
     */
    @java.lang.Override
    public boolean hasOptionalString() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string optional_string = 3;</code>
     * @return The optionalString.
     */
    @java.lang.Override
    public java.lang.String getOptionalString() {
      java.lang.Object ref = optionalString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        optionalString_ = s;
        return s;
      }
    }
    /**
     * <code>optional string optional_string = 3;</code>
     * @return The bytes for optionalString.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOptionalStringBytes() {
      java.lang.Object ref = optionalString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        optionalString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STRING_FIELD_NUMBER = 4;
    private volatile java.lang.Object string_;
    /**
     * <code>string string = 4;</code>
     * @return The string.
     */
    @java.lang.Override
    public java.lang.String getString() {
      java.lang.Object ref = string_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        string_ = s;
        return s;
      }
    }
    /**
     * <code>string string = 4;</code>
     * @return The bytes for string.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringBytes() {
      java.lang.Object ref = string_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        string_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPTIONAL_INT_FIELD_NUMBER = 5;
    private int optionalInt_;
    /**
     * <code>optional int32 optional_int = 5;</code>
     * @return Whether the optionalInt field is set.
     */
    @java.lang.Override
    public boolean hasOptionalInt() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 optional_int = 5;</code>
     * @return The optionalInt.
     */
    @java.lang.Override
    public int getOptionalInt() {
      return optionalInt_;
    }

    public static final int INT_FIELD_NUMBER = 6;
    private int int_;
    /**
     * <code>int32 int = 6;</code>
     * @return The int.
     */
    @java.lang.Override
    public int getInt() {
      return int_;
    }

    public static final int OPTIONAL_ENUM_FIELD_NUMBER = 7;
    private int optionalEnum_;
    /**
     * <code>optional .pbandk.testpb.Proto3PresenceEnum optional_enum = 7;</code>
     * @return Whether the optionalEnum field is set.
     */
    @java.lang.Override public boolean hasOptionalEnum() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .pbandk.testpb.Proto3PresenceEnum optional_enum = 7;</code>
     * @return The enum numeric value on the wire for optionalEnum.
     */
    @java.lang.Override public int getOptionalEnumValue() {
      return optionalEnum_;
    }
    /**
     * <code>optional .pbandk.testpb.Proto3PresenceEnum optional_enum = 7;</code>
     * @return The optionalEnum.
     */
    @java.lang.Override public pbandk.testpb.Proto3Presence.Proto3PresenceEnum getOptionalEnum() {
      @SuppressWarnings("deprecation")
      pbandk.testpb.Proto3Presence.Proto3PresenceEnum result = pbandk.testpb.Proto3Presence.Proto3PresenceEnum.valueOf(optionalEnum_);
      return result == null ? pbandk.testpb.Proto3Presence.Proto3PresenceEnum.UNRECOGNIZED : result;
    }

    public static final int ENUM_FIELD_NUMBER = 8;
    private int enum_;
    /**
     * <code>.pbandk.testpb.Proto3PresenceEnum enum = 8;</code>
     * @return The enum numeric value on the wire for enum.
     */
    @java.lang.Override public int getEnumValue() {
      return enum_;
    }
    /**
     * <code>.pbandk.testpb.Proto3PresenceEnum enum = 8;</code>
     * @return The enum.
     */
    @java.lang.Override public pbandk.testpb.Proto3Presence.Proto3PresenceEnum getEnum() {
      @SuppressWarnings("deprecation")
      pbandk.testpb.Proto3Presence.Proto3PresenceEnum result = pbandk.testpb.Proto3Presence.Proto3PresenceEnum.valueOf(enum_);
      return result == null ? pbandk.testpb.Proto3Presence.Proto3PresenceEnum.UNRECOGNIZED : result;
    }

    public static final int ONE_OF_STRING_FIELD_NUMBER = 9;
    /**
     * <code>string one_of_string = 9;</code>
     * @return Whether the oneOfString field is set.
     */
    public boolean hasOneOfString() {
      return oneOfCase_ == 9;
    }
    /**
     * <code>string one_of_string = 9;</code>
     * @return The oneOfString.
     */
    public java.lang.String getOneOfString() {
      java.lang.Object ref = "";
      if (oneOfCase_ == 9) {
        ref = oneOf_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (oneOfCase_ == 9) {
          oneOf_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string one_of_string = 9;</code>
     * @return The bytes for oneOfString.
     */
    public com.google.protobuf.ByteString
        getOneOfStringBytes() {
      java.lang.Object ref = "";
      if (oneOfCase_ == 9) {
        ref = oneOf_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (oneOfCase_ == 9) {
          oneOf_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ONE_OF_INT_FIELD_NUMBER = 10;
    /**
     * <code>int32 one_of_int = 10;</code>
     * @return Whether the oneOfInt field is set.
     */
    @java.lang.Override
    public boolean hasOneOfInt() {
      return oneOfCase_ == 10;
    }
    /**
     * <code>int32 one_of_int = 10;</code>
     * @return The oneOfInt.
     */
    @java.lang.Override
    public int getOneOfInt() {
      if (oneOfCase_ == 10) {
        return (java.lang.Integer) oneOf_;
      }
      return 0;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getOptionalMessage());
      }
      if (message_ != null) {
        output.writeMessage(2, getMessage());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, optionalString_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(string_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, string_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(5, optionalInt_);
      }
      if (int_ != 0) {
        output.writeInt32(6, int_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeEnum(7, optionalEnum_);
      }
      if (enum_ != pbandk.testpb.Proto3Presence.Proto3PresenceEnum.PROTO3_PRESENCE_ENUM_UNSPECIFIED.getNumber()) {
        output.writeEnum(8, enum_);
      }
      if (oneOfCase_ == 9) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, oneOf_);
      }
      if (oneOfCase_ == 10) {
        output.writeInt32(
            10, (int)((java.lang.Integer) oneOf_));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getOptionalMessage());
      }
      if (message_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMessage());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, optionalString_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(string_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, string_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, optionalInt_);
      }
      if (int_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, int_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, optionalEnum_);
      }
      if (enum_ != pbandk.testpb.Proto3Presence.Proto3PresenceEnum.PROTO3_PRESENCE_ENUM_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, enum_);
      }
      if (oneOfCase_ == 9) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, oneOf_);
      }
      if (oneOfCase_ == 10) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              10, (int)((java.lang.Integer) oneOf_));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pbandk.testpb.Proto3Presence.Proto3PresenceMain)) {
        return super.equals(obj);
      }
      pbandk.testpb.Proto3Presence.Proto3PresenceMain other = (pbandk.testpb.Proto3Presence.Proto3PresenceMain) obj;

      if (hasOptionalMessage() != other.hasOptionalMessage()) return false;
      if (hasOptionalMessage()) {
        if (!getOptionalMessage()
            .equals(other.getOptionalMessage())) return false;
      }
      if (hasMessage() != other.hasMessage()) return false;
      if (hasMessage()) {
        if (!getMessage()
            .equals(other.getMessage())) return false;
      }
      if (hasOptionalString() != other.hasOptionalString()) return false;
      if (hasOptionalString()) {
        if (!getOptionalString()
            .equals(other.getOptionalString())) return false;
      }
      if (!getString()
          .equals(other.getString())) return false;
      if (hasOptionalInt() != other.hasOptionalInt()) return false;
      if (hasOptionalInt()) {
        if (getOptionalInt()
            != other.getOptionalInt()) return false;
      }
      if (getInt()
          != other.getInt()) return false;
      if (hasOptionalEnum() != other.hasOptionalEnum()) return false;
      if (hasOptionalEnum()) {
        if (optionalEnum_ != other.optionalEnum_) return false;
      }
      if (enum_ != other.enum_) return false;
      if (!getOneOfCase().equals(other.getOneOfCase())) return false;
      switch (oneOfCase_) {
        case 9:
          if (!getOneOfString()
              .equals(other.getOneOfString())) return false;
          break;
        case 10:
          if (getOneOfInt()
              != other.getOneOfInt()) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOptionalMessage()) {
        hash = (37 * hash) + OPTIONAL_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getOptionalMessage().hashCode();
      }
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      if (hasOptionalString()) {
        hash = (37 * hash) + OPTIONAL_STRING_FIELD_NUMBER;
        hash = (53 * hash) + getOptionalString().hashCode();
      }
      hash = (37 * hash) + STRING_FIELD_NUMBER;
      hash = (53 * hash) + getString().hashCode();
      if (hasOptionalInt()) {
        hash = (37 * hash) + OPTIONAL_INT_FIELD_NUMBER;
        hash = (53 * hash) + getOptionalInt();
      }
      hash = (37 * hash) + INT_FIELD_NUMBER;
      hash = (53 * hash) + getInt();
      if (hasOptionalEnum()) {
        hash = (37 * hash) + OPTIONAL_ENUM_FIELD_NUMBER;
        hash = (53 * hash) + optionalEnum_;
      }
      hash = (37 * hash) + ENUM_FIELD_NUMBER;
      hash = (53 * hash) + enum_;
      switch (oneOfCase_) {
        case 9:
          hash = (37 * hash) + ONE_OF_STRING_FIELD_NUMBER;
          hash = (53 * hash) + getOneOfString().hashCode();
          break;
        case 10:
          hash = (37 * hash) + ONE_OF_INT_FIELD_NUMBER;
          hash = (53 * hash) + getOneOfInt();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pbandk.testpb.Proto3Presence.Proto3PresenceMain parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMain parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMain parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMain parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMain parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMain parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMain parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMain parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMain parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMain parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMain parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pbandk.testpb.Proto3Presence.Proto3PresenceMain parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pbandk.testpb.Proto3Presence.Proto3PresenceMain prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pbandk.testpb.Proto3PresenceMain}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pbandk.testpb.Proto3PresenceMain)
        pbandk.testpb.Proto3Presence.Proto3PresenceMainOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pbandk.testpb.Proto3Presence.internal_static_pbandk_testpb_Proto3PresenceMain_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pbandk.testpb.Proto3Presence.internal_static_pbandk_testpb_Proto3PresenceMain_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pbandk.testpb.Proto3Presence.Proto3PresenceMain.class, pbandk.testpb.Proto3Presence.Proto3PresenceMain.Builder.class);
      }

      // Construct using pbandk.testpb.Proto3Presence.Proto3PresenceMain.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOptionalMessageFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (optionalMessageBuilder_ == null) {
          optionalMessage_ = null;
        } else {
          optionalMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (messageBuilder_ == null) {
          message_ = null;
        } else {
          message_ = null;
          messageBuilder_ = null;
        }
        optionalString_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        string_ = "";

        optionalInt_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        int_ = 0;

        optionalEnum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        enum_ = 0;

        oneOfCase_ = 0;
        oneOf_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pbandk.testpb.Proto3Presence.internal_static_pbandk_testpb_Proto3PresenceMain_descriptor;
      }

      @java.lang.Override
      public pbandk.testpb.Proto3Presence.Proto3PresenceMain getDefaultInstanceForType() {
        return pbandk.testpb.Proto3Presence.Proto3PresenceMain.getDefaultInstance();
      }

      @java.lang.Override
      public pbandk.testpb.Proto3Presence.Proto3PresenceMain build() {
        pbandk.testpb.Proto3Presence.Proto3PresenceMain result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pbandk.testpb.Proto3Presence.Proto3PresenceMain buildPartial() {
        pbandk.testpb.Proto3Presence.Proto3PresenceMain result = new pbandk.testpb.Proto3Presence.Proto3PresenceMain(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (optionalMessageBuilder_ == null) {
            result.optionalMessage_ = optionalMessage_;
          } else {
            result.optionalMessage_ = optionalMessageBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (messageBuilder_ == null) {
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.optionalString_ = optionalString_;
        result.string_ = string_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.optionalInt_ = optionalInt_;
          to_bitField0_ |= 0x00000004;
        }
        result.int_ = int_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.optionalEnum_ = optionalEnum_;
        result.enum_ = enum_;
        if (oneOfCase_ == 9) {
          result.oneOf_ = oneOf_;
        }
        if (oneOfCase_ == 10) {
          result.oneOf_ = oneOf_;
        }
        result.bitField0_ = to_bitField0_;
        result.oneOfCase_ = oneOfCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pbandk.testpb.Proto3Presence.Proto3PresenceMain) {
          return mergeFrom((pbandk.testpb.Proto3Presence.Proto3PresenceMain)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pbandk.testpb.Proto3Presence.Proto3PresenceMain other) {
        if (other == pbandk.testpb.Proto3Presence.Proto3PresenceMain.getDefaultInstance()) return this;
        if (other.hasOptionalMessage()) {
          mergeOptionalMessage(other.getOptionalMessage());
        }
        if (other.hasMessage()) {
          mergeMessage(other.getMessage());
        }
        if (other.hasOptionalString()) {
          bitField0_ |= 0x00000002;
          optionalString_ = other.optionalString_;
          onChanged();
        }
        if (!other.getString().isEmpty()) {
          string_ = other.string_;
          onChanged();
        }
        if (other.hasOptionalInt()) {
          setOptionalInt(other.getOptionalInt());
        }
        if (other.getInt() != 0) {
          setInt(other.getInt());
        }
        if (other.hasOptionalEnum()) {
          setOptionalEnum(other.getOptionalEnum());
        }
        if (other.enum_ != 0) {
          setEnumValue(other.getEnumValue());
        }
        switch (other.getOneOfCase()) {
          case ONE_OF_STRING: {
            oneOfCase_ = 9;
            oneOf_ = other.oneOf_;
            onChanged();
            break;
          }
          case ONE_OF_INT: {
            setOneOfInt(other.getOneOfInt());
            break;
          }
          case ONEOF_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pbandk.testpb.Proto3Presence.Proto3PresenceMain parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pbandk.testpb.Proto3Presence.Proto3PresenceMain) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int oneOfCase_ = 0;
      private java.lang.Object oneOf_;
      public OneOfCase
          getOneOfCase() {
        return OneOfCase.forNumber(
            oneOfCase_);
      }

      public Builder clearOneOf() {
        oneOfCase_ = 0;
        oneOf_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private pbandk.testpb.Proto3Presence.Proto3PresenceMessage optionalMessage_;
      private com.google.protobuf.SingleFieldBuilderV3<
          pbandk.testpb.Proto3Presence.Proto3PresenceMessage, pbandk.testpb.Proto3Presence.Proto3PresenceMessage.Builder, pbandk.testpb.Proto3Presence.Proto3PresenceMessageOrBuilder> optionalMessageBuilder_;
      /**
       * <code>optional .pbandk.testpb.Proto3PresenceMessage optional_message = 1;</code>
       * @return Whether the optionalMessage field is set.
       */
      public boolean hasOptionalMessage() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .pbandk.testpb.Proto3PresenceMessage optional_message = 1;</code>
       * @return The optionalMessage.
       */
      public pbandk.testpb.Proto3Presence.Proto3PresenceMessage getOptionalMessage() {
        if (optionalMessageBuilder_ == null) {
          return optionalMessage_ == null ? pbandk.testpb.Proto3Presence.Proto3PresenceMessage.getDefaultInstance() : optionalMessage_;
        } else {
          return optionalMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .pbandk.testpb.Proto3PresenceMessage optional_message = 1;</code>
       */
      public Builder setOptionalMessage(pbandk.testpb.Proto3Presence.Proto3PresenceMessage value) {
        if (optionalMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          optionalMessage_ = value;
          onChanged();
        } else {
          optionalMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .pbandk.testpb.Proto3PresenceMessage optional_message = 1;</code>
       */
      public Builder setOptionalMessage(
          pbandk.testpb.Proto3Presence.Proto3PresenceMessage.Builder builderForValue) {
        if (optionalMessageBuilder_ == null) {
          optionalMessage_ = builderForValue.build();
          onChanged();
        } else {
          optionalMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .pbandk.testpb.Proto3PresenceMessage optional_message = 1;</code>
       */
      public Builder mergeOptionalMessage(pbandk.testpb.Proto3Presence.Proto3PresenceMessage value) {
        if (optionalMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              optionalMessage_ != null &&
              optionalMessage_ != pbandk.testpb.Proto3Presence.Proto3PresenceMessage.getDefaultInstance()) {
            optionalMessage_ =
              pbandk.testpb.Proto3Presence.Proto3PresenceMessage.newBuilder(optionalMessage_).mergeFrom(value).buildPartial();
          } else {
            optionalMessage_ = value;
          }
          onChanged();
        } else {
          optionalMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .pbandk.testpb.Proto3PresenceMessage optional_message = 1;</code>
       */
      public Builder clearOptionalMessage() {
        if (optionalMessageBuilder_ == null) {
          optionalMessage_ = null;
          onChanged();
        } else {
          optionalMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .pbandk.testpb.Proto3PresenceMessage optional_message = 1;</code>
       */
      public pbandk.testpb.Proto3Presence.Proto3PresenceMessage.Builder getOptionalMessageBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getOptionalMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .pbandk.testpb.Proto3PresenceMessage optional_message = 1;</code>
       */
      public pbandk.testpb.Proto3Presence.Proto3PresenceMessageOrBuilder getOptionalMessageOrBuilder() {
        if (optionalMessageBuilder_ != null) {
          return optionalMessageBuilder_.getMessageOrBuilder();
        } else {
          return optionalMessage_ == null ?
              pbandk.testpb.Proto3Presence.Proto3PresenceMessage.getDefaultInstance() : optionalMessage_;
        }
      }
      /**
       * <code>optional .pbandk.testpb.Proto3PresenceMessage optional_message = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pbandk.testpb.Proto3Presence.Proto3PresenceMessage, pbandk.testpb.Proto3Presence.Proto3PresenceMessage.Builder, pbandk.testpb.Proto3Presence.Proto3PresenceMessageOrBuilder> 
          getOptionalMessageFieldBuilder() {
        if (optionalMessageBuilder_ == null) {
          optionalMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pbandk.testpb.Proto3Presence.Proto3PresenceMessage, pbandk.testpb.Proto3Presence.Proto3PresenceMessage.Builder, pbandk.testpb.Proto3Presence.Proto3PresenceMessageOrBuilder>(
                  getOptionalMessage(),
                  getParentForChildren(),
                  isClean());
          optionalMessage_ = null;
        }
        return optionalMessageBuilder_;
      }

      private pbandk.testpb.Proto3Presence.Proto3PresenceMessage message_;
      private com.google.protobuf.SingleFieldBuilderV3<
          pbandk.testpb.Proto3Presence.Proto3PresenceMessage, pbandk.testpb.Proto3Presence.Proto3PresenceMessage.Builder, pbandk.testpb.Proto3Presence.Proto3PresenceMessageOrBuilder> messageBuilder_;
      /**
       * <code>.pbandk.testpb.Proto3PresenceMessage message = 2;</code>
       * @return Whether the message field is set.
       */
      public boolean hasMessage() {
        return messageBuilder_ != null || message_ != null;
      }
      /**
       * <code>.pbandk.testpb.Proto3PresenceMessage message = 2;</code>
       * @return The message.
       */
      public pbandk.testpb.Proto3Presence.Proto3PresenceMessage getMessage() {
        if (messageBuilder_ == null) {
          return message_ == null ? pbandk.testpb.Proto3Presence.Proto3PresenceMessage.getDefaultInstance() : message_;
        } else {
          return messageBuilder_.getMessage();
        }
      }
      /**
       * <code>.pbandk.testpb.Proto3PresenceMessage message = 2;</code>
       */
      public Builder setMessage(pbandk.testpb.Proto3Presence.Proto3PresenceMessage value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          messageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.pbandk.testpb.Proto3PresenceMessage message = 2;</code>
       */
      public Builder setMessage(
          pbandk.testpb.Proto3Presence.Proto3PresenceMessage.Builder builderForValue) {
        if (messageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.pbandk.testpb.Proto3PresenceMessage message = 2;</code>
       */
      public Builder mergeMessage(pbandk.testpb.Proto3Presence.Proto3PresenceMessage value) {
        if (messageBuilder_ == null) {
          if (message_ != null) {
            message_ =
              pbandk.testpb.Proto3Presence.Proto3PresenceMessage.newBuilder(message_).mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          messageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.pbandk.testpb.Proto3PresenceMessage message = 2;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = null;
          onChanged();
        } else {
          message_ = null;
          messageBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.pbandk.testpb.Proto3PresenceMessage message = 2;</code>
       */
      public pbandk.testpb.Proto3Presence.Proto3PresenceMessage.Builder getMessageBuilder() {
        
        onChanged();
        return getMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.pbandk.testpb.Proto3PresenceMessage message = 2;</code>
       */
      public pbandk.testpb.Proto3Presence.Proto3PresenceMessageOrBuilder getMessageOrBuilder() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          return message_ == null ?
              pbandk.testpb.Proto3Presence.Proto3PresenceMessage.getDefaultInstance() : message_;
        }
      }
      /**
       * <code>.pbandk.testpb.Proto3PresenceMessage message = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pbandk.testpb.Proto3Presence.Proto3PresenceMessage, pbandk.testpb.Proto3Presence.Proto3PresenceMessage.Builder, pbandk.testpb.Proto3Presence.Proto3PresenceMessageOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pbandk.testpb.Proto3Presence.Proto3PresenceMessage, pbandk.testpb.Proto3Presence.Proto3PresenceMessage.Builder, pbandk.testpb.Proto3Presence.Proto3PresenceMessageOrBuilder>(
                  getMessage(),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }

      private java.lang.Object optionalString_ = "";
      /**
       * <code>optional string optional_string = 3;</code>
       * @return Whether the optionalString field is set.
       */
      public boolean hasOptionalString() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string optional_string = 3;</code>
       * @return The optionalString.
       */
      public java.lang.String getOptionalString() {
        java.lang.Object ref = optionalString_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          optionalString_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string optional_string = 3;</code>
       * @return The bytes for optionalString.
       */
      public com.google.protobuf.ByteString
          getOptionalStringBytes() {
        java.lang.Object ref = optionalString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          optionalString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string optional_string = 3;</code>
       * @param value The optionalString to set.
       * @return This builder for chaining.
       */
      public Builder setOptionalString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        optionalString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string optional_string = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOptionalString() {
        bitField0_ = (bitField0_ & ~0x00000002);
        optionalString_ = getDefaultInstance().getOptionalString();
        onChanged();
        return this;
      }
      /**
       * <code>optional string optional_string = 3;</code>
       * @param value The bytes for optionalString to set.
       * @return This builder for chaining.
       */
      public Builder setOptionalStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000002;
        optionalString_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object string_ = "";
      /**
       * <code>string string = 4;</code>
       * @return The string.
       */
      public java.lang.String getString() {
        java.lang.Object ref = string_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          string_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string string = 4;</code>
       * @return The bytes for string.
       */
      public com.google.protobuf.ByteString
          getStringBytes() {
        java.lang.Object ref = string_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          string_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string string = 4;</code>
       * @param value The string to set.
       * @return This builder for chaining.
       */
      public Builder setString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        string_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string string = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearString() {
        
        string_ = getDefaultInstance().getString();
        onChanged();
        return this;
      }
      /**
       * <code>string string = 4;</code>
       * @param value The bytes for string to set.
       * @return This builder for chaining.
       */
      public Builder setStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        string_ = value;
        onChanged();
        return this;
      }

      private int optionalInt_ ;
      /**
       * <code>optional int32 optional_int = 5;</code>
       * @return Whether the optionalInt field is set.
       */
      @java.lang.Override
      public boolean hasOptionalInt() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 optional_int = 5;</code>
       * @return The optionalInt.
       */
      @java.lang.Override
      public int getOptionalInt() {
        return optionalInt_;
      }
      /**
       * <code>optional int32 optional_int = 5;</code>
       * @param value The optionalInt to set.
       * @return This builder for chaining.
       */
      public Builder setOptionalInt(int value) {
        bitField0_ |= 0x00000004;
        optionalInt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 optional_int = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOptionalInt() {
        bitField0_ = (bitField0_ & ~0x00000004);
        optionalInt_ = 0;
        onChanged();
        return this;
      }

      private int int_ ;
      /**
       * <code>int32 int = 6;</code>
       * @return The int.
       */
      @java.lang.Override
      public int getInt() {
        return int_;
      }
      /**
       * <code>int32 int = 6;</code>
       * @param value The int to set.
       * @return This builder for chaining.
       */
      public Builder setInt(int value) {
        
        int_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 int = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearInt() {
        
        int_ = 0;
        onChanged();
        return this;
      }

      private int optionalEnum_ = 0;
      /**
       * <code>optional .pbandk.testpb.Proto3PresenceEnum optional_enum = 7;</code>
       * @return Whether the optionalEnum field is set.
       */
      @java.lang.Override public boolean hasOptionalEnum() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .pbandk.testpb.Proto3PresenceEnum optional_enum = 7;</code>
       * @return The enum numeric value on the wire for optionalEnum.
       */
      @java.lang.Override public int getOptionalEnumValue() {
        return optionalEnum_;
      }
      /**
       * <code>optional .pbandk.testpb.Proto3PresenceEnum optional_enum = 7;</code>
       * @param value The enum numeric value on the wire for optionalEnum to set.
       * @return This builder for chaining.
       */
      public Builder setOptionalEnumValue(int value) {
        bitField0_ |= 0x00000008;
        optionalEnum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .pbandk.testpb.Proto3PresenceEnum optional_enum = 7;</code>
       * @return The optionalEnum.
       */
      @java.lang.Override
      public pbandk.testpb.Proto3Presence.Proto3PresenceEnum getOptionalEnum() {
        @SuppressWarnings("deprecation")
        pbandk.testpb.Proto3Presence.Proto3PresenceEnum result = pbandk.testpb.Proto3Presence.Proto3PresenceEnum.valueOf(optionalEnum_);
        return result == null ? pbandk.testpb.Proto3Presence.Proto3PresenceEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .pbandk.testpb.Proto3PresenceEnum optional_enum = 7;</code>
       * @param value The optionalEnum to set.
       * @return This builder for chaining.
       */
      public Builder setOptionalEnum(pbandk.testpb.Proto3Presence.Proto3PresenceEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        optionalEnum_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .pbandk.testpb.Proto3PresenceEnum optional_enum = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearOptionalEnum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        optionalEnum_ = 0;
        onChanged();
        return this;
      }

      private int enum_ = 0;
      /**
       * <code>.pbandk.testpb.Proto3PresenceEnum enum = 8;</code>
       * @return The enum numeric value on the wire for enum.
       */
      @java.lang.Override public int getEnumValue() {
        return enum_;
      }
      /**
       * <code>.pbandk.testpb.Proto3PresenceEnum enum = 8;</code>
       * @param value The enum numeric value on the wire for enum to set.
       * @return This builder for chaining.
       */
      public Builder setEnumValue(int value) {
        
        enum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.pbandk.testpb.Proto3PresenceEnum enum = 8;</code>
       * @return The enum.
       */
      @java.lang.Override
      public pbandk.testpb.Proto3Presence.Proto3PresenceEnum getEnum() {
        @SuppressWarnings("deprecation")
        pbandk.testpb.Proto3Presence.Proto3PresenceEnum result = pbandk.testpb.Proto3Presence.Proto3PresenceEnum.valueOf(enum_);
        return result == null ? pbandk.testpb.Proto3Presence.Proto3PresenceEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.pbandk.testpb.Proto3PresenceEnum enum = 8;</code>
       * @param value The enum to set.
       * @return This builder for chaining.
       */
      public Builder setEnum(pbandk.testpb.Proto3Presence.Proto3PresenceEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        enum_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.pbandk.testpb.Proto3PresenceEnum enum = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnum() {
        
        enum_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>string one_of_string = 9;</code>
       * @return Whether the oneOfString field is set.
       */
      @java.lang.Override
      public boolean hasOneOfString() {
        return oneOfCase_ == 9;
      }
      /**
       * <code>string one_of_string = 9;</code>
       * @return The oneOfString.
       */
      @java.lang.Override
      public java.lang.String getOneOfString() {
        java.lang.Object ref = "";
        if (oneOfCase_ == 9) {
          ref = oneOf_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (oneOfCase_ == 9) {
            oneOf_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string one_of_string = 9;</code>
       * @return The bytes for oneOfString.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getOneOfStringBytes() {
        java.lang.Object ref = "";
        if (oneOfCase_ == 9) {
          ref = oneOf_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (oneOfCase_ == 9) {
            oneOf_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string one_of_string = 9;</code>
       * @param value The oneOfString to set.
       * @return This builder for chaining.
       */
      public Builder setOneOfString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  oneOfCase_ = 9;
        oneOf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string one_of_string = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearOneOfString() {
        if (oneOfCase_ == 9) {
          oneOfCase_ = 0;
          oneOf_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string one_of_string = 9;</code>
       * @param value The bytes for oneOfString to set.
       * @return This builder for chaining.
       */
      public Builder setOneOfStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        oneOfCase_ = 9;
        oneOf_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 one_of_int = 10;</code>
       * @return Whether the oneOfInt field is set.
       */
      public boolean hasOneOfInt() {
        return oneOfCase_ == 10;
      }
      /**
       * <code>int32 one_of_int = 10;</code>
       * @return The oneOfInt.
       */
      public int getOneOfInt() {
        if (oneOfCase_ == 10) {
          return (java.lang.Integer) oneOf_;
        }
        return 0;
      }
      /**
       * <code>int32 one_of_int = 10;</code>
       * @param value The oneOfInt to set.
       * @return This builder for chaining.
       */
      public Builder setOneOfInt(int value) {
        oneOfCase_ = 10;
        oneOf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 one_of_int = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearOneOfInt() {
        if (oneOfCase_ == 10) {
          oneOfCase_ = 0;
          oneOf_ = null;
          onChanged();
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pbandk.testpb.Proto3PresenceMain)
    }

    // @@protoc_insertion_point(class_scope:pbandk.testpb.Proto3PresenceMain)
    private static final pbandk.testpb.Proto3Presence.Proto3PresenceMain DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbandk.testpb.Proto3Presence.Proto3PresenceMain();
    }

    public static pbandk.testpb.Proto3Presence.Proto3PresenceMain getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Proto3PresenceMain>
        PARSER = new com.google.protobuf.AbstractParser<Proto3PresenceMain>() {
      @java.lang.Override
      public Proto3PresenceMain parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Proto3PresenceMain(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Proto3PresenceMain> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Proto3PresenceMain> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pbandk.testpb.Proto3Presence.Proto3PresenceMain getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbandk_testpb_Proto3PresenceMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbandk_testpb_Proto3PresenceMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbandk_testpb_Proto3PresenceMain_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbandk_testpb_Proto3PresenceMain_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$pbandk/testpb/proto_3_presence.proto\022\r" +
      "pbandk.testpb\"$\n\025Proto3PresenceMessage\022\013" +
      "\n\003int\030\001 \001(\005\"\332\003\n\022Proto3PresenceMain\022C\n\020op" +
      "tional_message\030\001 \001(\0132$.pbandk.testpb.Pro" +
      "to3PresenceMessageH\001\210\001\001\0225\n\007message\030\002 \001(\013" +
      "2$.pbandk.testpb.Proto3PresenceMessage\022\034" +
      "\n\017optional_string\030\003 \001(\tH\002\210\001\001\022\016\n\006string\030\004" +
      " \001(\t\022\031\n\014optional_int\030\005 \001(\005H\003\210\001\001\022\013\n\003int\030\006" +
      " \001(\005\022=\n\roptional_enum\030\007 \001(\0162!.pbandk.tes" +
      "tpb.Proto3PresenceEnumH\004\210\001\001\022/\n\004enum\030\010 \001(" +
      "\0162!.pbandk.testpb.Proto3PresenceEnum\022\027\n\r" +
      "one_of_string\030\t \001(\tH\000\022\024\n\none_of_int\030\n \001(" +
      "\005H\000B\007\n\005oneOfB\023\n\021_optional_messageB\022\n\020_op" +
      "tional_stringB\017\n\r_optional_intB\020\n\016_optio" +
      "nal_enum*^\n\022Proto3PresenceEnum\022$\n PROTO3" +
      "_PRESENCE_ENUM_UNSPECIFIED\020\000\022\"\n\036PROTO3_P" +
      "RESENCE_ENUM_SPECIFIED\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pbandk_testpb_Proto3PresenceMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pbandk_testpb_Proto3PresenceMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbandk_testpb_Proto3PresenceMessage_descriptor,
        new java.lang.String[] { "Int", });
    internal_static_pbandk_testpb_Proto3PresenceMain_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pbandk_testpb_Proto3PresenceMain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbandk_testpb_Proto3PresenceMain_descriptor,
        new java.lang.String[] { "OptionalMessage", "Message", "OptionalString", "String", "OptionalInt", "Int", "OptionalEnum", "Enum", "OneOfString", "OneOfInt", "OneOf", "OptionalMessage", "OptionalString", "OptionalInt", "OptionalEnum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
