// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbandk/testpb/custom_options.proto

package pbandk.testpb;

public final class CustomOptions {
  private CustomOptions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SingleRequiredCustomOptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbandk.testpb.SingleRequiredCustomOption)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string single = 1 [(.pbandk.testpb.rules) = { ... }</code>
     * @return The single.
     */
    java.lang.String getSingle();
    /**
     * <code>string single = 1 [(.pbandk.testpb.rules) = { ... }</code>
     * @return The bytes for single.
     */
    com.google.protobuf.ByteString
        getSingleBytes();
  }
  /**
   * Protobuf type {@code pbandk.testpb.SingleRequiredCustomOption}
   */
  public static final class SingleRequiredCustomOption extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pbandk.testpb.SingleRequiredCustomOption)
      SingleRequiredCustomOptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SingleRequiredCustomOption.newBuilder() to construct.
    private SingleRequiredCustomOption(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SingleRequiredCustomOption() {
      single_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SingleRequiredCustomOption();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SingleRequiredCustomOption(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              single_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pbandk.testpb.CustomOptions.internal_static_pbandk_testpb_SingleRequiredCustomOption_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pbandk.testpb.CustomOptions.internal_static_pbandk_testpb_SingleRequiredCustomOption_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pbandk.testpb.CustomOptions.SingleRequiredCustomOption.class, pbandk.testpb.CustomOptions.SingleRequiredCustomOption.Builder.class);
    }

    public static final int SINGLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object single_;
    /**
     * <code>string single = 1 [(.pbandk.testpb.rules) = { ... }</code>
     * @return The single.
     */
    @java.lang.Override
    public java.lang.String getSingle() {
      java.lang.Object ref = single_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        single_ = s;
        return s;
      }
    }
    /**
     * <code>string single = 1 [(.pbandk.testpb.rules) = { ... }</code>
     * @return The bytes for single.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSingleBytes() {
      java.lang.Object ref = single_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        single_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(single_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, single_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(single_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, single_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pbandk.testpb.CustomOptions.SingleRequiredCustomOption)) {
        return super.equals(obj);
      }
      pbandk.testpb.CustomOptions.SingleRequiredCustomOption other = (pbandk.testpb.CustomOptions.SingleRequiredCustomOption) obj;

      if (!getSingle()
          .equals(other.getSingle())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SINGLE_FIELD_NUMBER;
      hash = (53 * hash) + getSingle().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pbandk.testpb.CustomOptions.SingleRequiredCustomOption parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pbandk.testpb.CustomOptions.SingleRequiredCustomOption parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pbandk.testpb.CustomOptions.SingleRequiredCustomOption parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pbandk.testpb.CustomOptions.SingleRequiredCustomOption parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pbandk.testpb.CustomOptions.SingleRequiredCustomOption parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pbandk.testpb.CustomOptions.SingleRequiredCustomOption parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pbandk.testpb.CustomOptions.SingleRequiredCustomOption parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pbandk.testpb.CustomOptions.SingleRequiredCustomOption parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pbandk.testpb.CustomOptions.SingleRequiredCustomOption parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pbandk.testpb.CustomOptions.SingleRequiredCustomOption parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pbandk.testpb.CustomOptions.SingleRequiredCustomOption parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pbandk.testpb.CustomOptions.SingleRequiredCustomOption parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pbandk.testpb.CustomOptions.SingleRequiredCustomOption prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pbandk.testpb.SingleRequiredCustomOption}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pbandk.testpb.SingleRequiredCustomOption)
        pbandk.testpb.CustomOptions.SingleRequiredCustomOptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pbandk.testpb.CustomOptions.internal_static_pbandk_testpb_SingleRequiredCustomOption_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pbandk.testpb.CustomOptions.internal_static_pbandk_testpb_SingleRequiredCustomOption_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pbandk.testpb.CustomOptions.SingleRequiredCustomOption.class, pbandk.testpb.CustomOptions.SingleRequiredCustomOption.Builder.class);
      }

      // Construct using pbandk.testpb.CustomOptions.SingleRequiredCustomOption.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        single_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pbandk.testpb.CustomOptions.internal_static_pbandk_testpb_SingleRequiredCustomOption_descriptor;
      }

      @java.lang.Override
      public pbandk.testpb.CustomOptions.SingleRequiredCustomOption getDefaultInstanceForType() {
        return pbandk.testpb.CustomOptions.SingleRequiredCustomOption.getDefaultInstance();
      }

      @java.lang.Override
      public pbandk.testpb.CustomOptions.SingleRequiredCustomOption build() {
        pbandk.testpb.CustomOptions.SingleRequiredCustomOption result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pbandk.testpb.CustomOptions.SingleRequiredCustomOption buildPartial() {
        pbandk.testpb.CustomOptions.SingleRequiredCustomOption result = new pbandk.testpb.CustomOptions.SingleRequiredCustomOption(this);
        result.single_ = single_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pbandk.testpb.CustomOptions.SingleRequiredCustomOption) {
          return mergeFrom((pbandk.testpb.CustomOptions.SingleRequiredCustomOption)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pbandk.testpb.CustomOptions.SingleRequiredCustomOption other) {
        if (other == pbandk.testpb.CustomOptions.SingleRequiredCustomOption.getDefaultInstance()) return this;
        if (!other.getSingle().isEmpty()) {
          single_ = other.single_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pbandk.testpb.CustomOptions.SingleRequiredCustomOption parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pbandk.testpb.CustomOptions.SingleRequiredCustomOption) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object single_ = "";
      /**
       * <code>string single = 1 [(.pbandk.testpb.rules) = { ... }</code>
       * @return The single.
       */
      public java.lang.String getSingle() {
        java.lang.Object ref = single_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          single_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string single = 1 [(.pbandk.testpb.rules) = { ... }</code>
       * @return The bytes for single.
       */
      public com.google.protobuf.ByteString
          getSingleBytes() {
        java.lang.Object ref = single_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          single_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string single = 1 [(.pbandk.testpb.rules) = { ... }</code>
       * @param value The single to set.
       * @return This builder for chaining.
       */
      public Builder setSingle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        single_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string single = 1 [(.pbandk.testpb.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearSingle() {
        
        single_ = getDefaultInstance().getSingle();
        onChanged();
        return this;
      }
      /**
       * <code>string single = 1 [(.pbandk.testpb.rules) = { ... }</code>
       * @param value The bytes for single to set.
       * @return This builder for chaining.
       */
      public Builder setSingleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        single_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pbandk.testpb.SingleRequiredCustomOption)
    }

    // @@protoc_insertion_point(class_scope:pbandk.testpb.SingleRequiredCustomOption)
    private static final pbandk.testpb.CustomOptions.SingleRequiredCustomOption DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbandk.testpb.CustomOptions.SingleRequiredCustomOption();
    }

    public static pbandk.testpb.CustomOptions.SingleRequiredCustomOption getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SingleRequiredCustomOption>
        PARSER = new com.google.protobuf.AbstractParser<SingleRequiredCustomOption>() {
      @java.lang.Override
      public SingleRequiredCustomOption parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SingleRequiredCustomOption(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SingleRequiredCustomOption> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SingleRequiredCustomOption> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pbandk.testpb.CustomOptions.SingleRequiredCustomOption getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MultipleCustomOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbandk.testpb.MultipleCustomOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string multiple = 1 [(.pbandk.testpb.rules) = { ... }</code>
     * @return The multiple.
     */
    java.lang.String getMultiple();
    /**
     * <code>string multiple = 1 [(.pbandk.testpb.rules) = { ... }</code>
     * @return The bytes for multiple.
     */
    com.google.protobuf.ByteString
        getMultipleBytes();
  }
  /**
   * Protobuf type {@code pbandk.testpb.MultipleCustomOptions}
   */
  public static final class MultipleCustomOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pbandk.testpb.MultipleCustomOptions)
      MultipleCustomOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MultipleCustomOptions.newBuilder() to construct.
    private MultipleCustomOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultipleCustomOptions() {
      multiple_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MultipleCustomOptions();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MultipleCustomOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              multiple_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pbandk.testpb.CustomOptions.internal_static_pbandk_testpb_MultipleCustomOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pbandk.testpb.CustomOptions.internal_static_pbandk_testpb_MultipleCustomOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pbandk.testpb.CustomOptions.MultipleCustomOptions.class, pbandk.testpb.CustomOptions.MultipleCustomOptions.Builder.class);
    }

    public static final int MULTIPLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object multiple_;
    /**
     * <code>string multiple = 1 [(.pbandk.testpb.rules) = { ... }</code>
     * @return The multiple.
     */
    @java.lang.Override
    public java.lang.String getMultiple() {
      java.lang.Object ref = multiple_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        multiple_ = s;
        return s;
      }
    }
    /**
     * <code>string multiple = 1 [(.pbandk.testpb.rules) = { ... }</code>
     * @return The bytes for multiple.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMultipleBytes() {
      java.lang.Object ref = multiple_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        multiple_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(multiple_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, multiple_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(multiple_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, multiple_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pbandk.testpb.CustomOptions.MultipleCustomOptions)) {
        return super.equals(obj);
      }
      pbandk.testpb.CustomOptions.MultipleCustomOptions other = (pbandk.testpb.CustomOptions.MultipleCustomOptions) obj;

      if (!getMultiple()
          .equals(other.getMultiple())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MULTIPLE_FIELD_NUMBER;
      hash = (53 * hash) + getMultiple().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pbandk.testpb.CustomOptions.MultipleCustomOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pbandk.testpb.CustomOptions.MultipleCustomOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pbandk.testpb.MultipleCustomOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pbandk.testpb.MultipleCustomOptions)
        pbandk.testpb.CustomOptions.MultipleCustomOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pbandk.testpb.CustomOptions.internal_static_pbandk_testpb_MultipleCustomOptions_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pbandk.testpb.CustomOptions.internal_static_pbandk_testpb_MultipleCustomOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pbandk.testpb.CustomOptions.MultipleCustomOptions.class, pbandk.testpb.CustomOptions.MultipleCustomOptions.Builder.class);
      }

      // Construct using pbandk.testpb.CustomOptions.MultipleCustomOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        multiple_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pbandk.testpb.CustomOptions.internal_static_pbandk_testpb_MultipleCustomOptions_descriptor;
      }

      @java.lang.Override
      public pbandk.testpb.CustomOptions.MultipleCustomOptions getDefaultInstanceForType() {
        return pbandk.testpb.CustomOptions.MultipleCustomOptions.getDefaultInstance();
      }

      @java.lang.Override
      public pbandk.testpb.CustomOptions.MultipleCustomOptions build() {
        pbandk.testpb.CustomOptions.MultipleCustomOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pbandk.testpb.CustomOptions.MultipleCustomOptions buildPartial() {
        pbandk.testpb.CustomOptions.MultipleCustomOptions result = new pbandk.testpb.CustomOptions.MultipleCustomOptions(this);
        result.multiple_ = multiple_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pbandk.testpb.CustomOptions.MultipleCustomOptions) {
          return mergeFrom((pbandk.testpb.CustomOptions.MultipleCustomOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pbandk.testpb.CustomOptions.MultipleCustomOptions other) {
        if (other == pbandk.testpb.CustomOptions.MultipleCustomOptions.getDefaultInstance()) return this;
        if (!other.getMultiple().isEmpty()) {
          multiple_ = other.multiple_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pbandk.testpb.CustomOptions.MultipleCustomOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pbandk.testpb.CustomOptions.MultipleCustomOptions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object multiple_ = "";
      /**
       * <code>string multiple = 1 [(.pbandk.testpb.rules) = { ... }</code>
       * @return The multiple.
       */
      public java.lang.String getMultiple() {
        java.lang.Object ref = multiple_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          multiple_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string multiple = 1 [(.pbandk.testpb.rules) = { ... }</code>
       * @return The bytes for multiple.
       */
      public com.google.protobuf.ByteString
          getMultipleBytes() {
        java.lang.Object ref = multiple_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          multiple_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string multiple = 1 [(.pbandk.testpb.rules) = { ... }</code>
       * @param value The multiple to set.
       * @return This builder for chaining.
       */
      public Builder setMultiple(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        multiple_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string multiple = 1 [(.pbandk.testpb.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearMultiple() {
        
        multiple_ = getDefaultInstance().getMultiple();
        onChanged();
        return this;
      }
      /**
       * <code>string multiple = 1 [(.pbandk.testpb.rules) = { ... }</code>
       * @param value The bytes for multiple to set.
       * @return This builder for chaining.
       */
      public Builder setMultipleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        multiple_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pbandk.testpb.MultipleCustomOptions)
    }

    // @@protoc_insertion_point(class_scope:pbandk.testpb.MultipleCustomOptions)
    private static final pbandk.testpb.CustomOptions.MultipleCustomOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbandk.testpb.CustomOptions.MultipleCustomOptions();
    }

    public static pbandk.testpb.CustomOptions.MultipleCustomOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultipleCustomOptions>
        PARSER = new com.google.protobuf.AbstractParser<MultipleCustomOptions>() {
      @java.lang.Override
      public MultipleCustomOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultipleCustomOptions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MultipleCustomOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultipleCustomOptions> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pbandk.testpb.CustomOptions.MultipleCustomOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MultipleCustomOptionsPlusDeprecatedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbandk.testpb.MultipleCustomOptionsPlusDeprecated)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string multiple_deprecated = 1 [deprecated = true, (.pbandk.testpb.rules) = { ... }</code>
     * @deprecated
     * @return The multipleDeprecated.
     */
    @java.lang.Deprecated java.lang.String getMultipleDeprecated();
    /**
     * <code>string multiple_deprecated = 1 [deprecated = true, (.pbandk.testpb.rules) = { ... }</code>
     * @deprecated
     * @return The bytes for multipleDeprecated.
     */
    @java.lang.Deprecated com.google.protobuf.ByteString
        getMultipleDeprecatedBytes();
  }
  /**
   * Protobuf type {@code pbandk.testpb.MultipleCustomOptionsPlusDeprecated}
   */
  public static final class MultipleCustomOptionsPlusDeprecated extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pbandk.testpb.MultipleCustomOptionsPlusDeprecated)
      MultipleCustomOptionsPlusDeprecatedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MultipleCustomOptionsPlusDeprecated.newBuilder() to construct.
    private MultipleCustomOptionsPlusDeprecated(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultipleCustomOptionsPlusDeprecated() {
      multipleDeprecated_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MultipleCustomOptionsPlusDeprecated();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MultipleCustomOptionsPlusDeprecated(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              multipleDeprecated_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pbandk.testpb.CustomOptions.internal_static_pbandk_testpb_MultipleCustomOptionsPlusDeprecated_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pbandk.testpb.CustomOptions.internal_static_pbandk_testpb_MultipleCustomOptionsPlusDeprecated_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated.class, pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated.Builder.class);
    }

    public static final int MULTIPLE_DEPRECATED_FIELD_NUMBER = 1;
    private volatile java.lang.Object multipleDeprecated_;
    /**
     * <code>string multiple_deprecated = 1 [deprecated = true, (.pbandk.testpb.rules) = { ... }</code>
     * @deprecated
     * @return The multipleDeprecated.
     */
    @java.lang.Override
    @java.lang.Deprecated public java.lang.String getMultipleDeprecated() {
      java.lang.Object ref = multipleDeprecated_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        multipleDeprecated_ = s;
        return s;
      }
    }
    /**
     * <code>string multiple_deprecated = 1 [deprecated = true, (.pbandk.testpb.rules) = { ... }</code>
     * @deprecated
     * @return The bytes for multipleDeprecated.
     */
    @java.lang.Override
    @java.lang.Deprecated public com.google.protobuf.ByteString
        getMultipleDeprecatedBytes() {
      java.lang.Object ref = multipleDeprecated_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        multipleDeprecated_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(multipleDeprecated_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, multipleDeprecated_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(multipleDeprecated_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, multipleDeprecated_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated)) {
        return super.equals(obj);
      }
      pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated other = (pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated) obj;

      if (!getMultipleDeprecated()
          .equals(other.getMultipleDeprecated())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MULTIPLE_DEPRECATED_FIELD_NUMBER;
      hash = (53 * hash) + getMultipleDeprecated().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pbandk.testpb.MultipleCustomOptionsPlusDeprecated}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pbandk.testpb.MultipleCustomOptionsPlusDeprecated)
        pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecatedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pbandk.testpb.CustomOptions.internal_static_pbandk_testpb_MultipleCustomOptionsPlusDeprecated_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pbandk.testpb.CustomOptions.internal_static_pbandk_testpb_MultipleCustomOptionsPlusDeprecated_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated.class, pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated.Builder.class);
      }

      // Construct using pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        multipleDeprecated_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pbandk.testpb.CustomOptions.internal_static_pbandk_testpb_MultipleCustomOptionsPlusDeprecated_descriptor;
      }

      @java.lang.Override
      public pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated getDefaultInstanceForType() {
        return pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated.getDefaultInstance();
      }

      @java.lang.Override
      public pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated build() {
        pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated buildPartial() {
        pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated result = new pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated(this);
        result.multipleDeprecated_ = multipleDeprecated_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated) {
          return mergeFrom((pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated other) {
        if (other == pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated.getDefaultInstance()) return this;
        if (!other.getMultipleDeprecated().isEmpty()) {
          multipleDeprecated_ = other.multipleDeprecated_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object multipleDeprecated_ = "";
      /**
       * <code>string multiple_deprecated = 1 [deprecated = true, (.pbandk.testpb.rules) = { ... }</code>
       * @deprecated
       * @return The multipleDeprecated.
       */
      @java.lang.Deprecated public java.lang.String getMultipleDeprecated() {
        java.lang.Object ref = multipleDeprecated_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          multipleDeprecated_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string multiple_deprecated = 1 [deprecated = true, (.pbandk.testpb.rules) = { ... }</code>
       * @deprecated
       * @return The bytes for multipleDeprecated.
       */
      @java.lang.Deprecated public com.google.protobuf.ByteString
          getMultipleDeprecatedBytes() {
        java.lang.Object ref = multipleDeprecated_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          multipleDeprecated_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string multiple_deprecated = 1 [deprecated = true, (.pbandk.testpb.rules) = { ... }</code>
       * @deprecated
       * @param value The multipleDeprecated to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setMultipleDeprecated(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        multipleDeprecated_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string multiple_deprecated = 1 [deprecated = true, (.pbandk.testpb.rules) = { ... }</code>
       * @deprecated
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder clearMultipleDeprecated() {
        
        multipleDeprecated_ = getDefaultInstance().getMultipleDeprecated();
        onChanged();
        return this;
      }
      /**
       * <code>string multiple_deprecated = 1 [deprecated = true, (.pbandk.testpb.rules) = { ... }</code>
       * @deprecated
       * @param value The bytes for multipleDeprecated to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setMultipleDeprecatedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        multipleDeprecated_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pbandk.testpb.MultipleCustomOptionsPlusDeprecated)
    }

    // @@protoc_insertion_point(class_scope:pbandk.testpb.MultipleCustomOptionsPlusDeprecated)
    private static final pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated();
    }

    public static pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultipleCustomOptionsPlusDeprecated>
        PARSER = new com.google.protobuf.AbstractParser<MultipleCustomOptionsPlusDeprecated>() {
      @java.lang.Override
      public MultipleCustomOptionsPlusDeprecated parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultipleCustomOptionsPlusDeprecated(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MultipleCustomOptionsPlusDeprecated> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultipleCustomOptionsPlusDeprecated> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pbandk.testpb.CustomOptions.MultipleCustomOptionsPlusDeprecated getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbandk_testpb_SingleRequiredCustomOption_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbandk_testpb_SingleRequiredCustomOption_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbandk_testpb_MultipleCustomOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbandk_testpb_MultipleCustomOptions_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbandk_testpb_MultipleCustomOptionsPlusDeprecated_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbandk_testpb_MultipleCustomOptionsPlusDeprecated_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"pbandk/testpb/custom_options.proto\022\rpb" +
      "andk.testpb\032\034pbandk/testpb/validate.prot" +
      "o\"6\n\032SingleRequiredCustomOption\022\030\n\006singl" +
      "e\030\001 \001(\tB\010\372B\005\212\001\002\020\001\":\n\025MultipleCustomOptio" +
      "ns\022!\n\010multiple\030\001 \001(\tB\017\372B\005\212\001\002\020\001\372B\004r\002\020\n\"T\n" +
      "#MultipleCustomOptionsPlusDeprecated\022-\n\023" +
      "multiple_deprecated\030\001 \001(\tB\020\030\001\372B\004r\002\030 \372B\004r" +
      "\002\020\nb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pbandk.testpb.Validate.getDescriptor(),
        });
    internal_static_pbandk_testpb_SingleRequiredCustomOption_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pbandk_testpb_SingleRequiredCustomOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbandk_testpb_SingleRequiredCustomOption_descriptor,
        new java.lang.String[] { "Single", });
    internal_static_pbandk_testpb_MultipleCustomOptions_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pbandk_testpb_MultipleCustomOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbandk_testpb_MultipleCustomOptions_descriptor,
        new java.lang.String[] { "Multiple", });
    internal_static_pbandk_testpb_MultipleCustomOptionsPlusDeprecated_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pbandk_testpb_MultipleCustomOptionsPlusDeprecated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbandk_testpb_MultipleCustomOptionsPlusDeprecated_descriptor,
        new java.lang.String[] { "MultipleDeprecated", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(pbandk.testpb.Validate.rules);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    pbandk.testpb.Validate.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
