// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbandk/testpb/proto3_extensions.proto

package pbandk.testpb;

public final class Proto3Extensions {
  private Proto3Extensions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(pbandk.testpb.Proto3Extensions.nonOptionalInt32);
    registry.add(pbandk.testpb.Proto3Extensions.optionalInt32);
    registry.add(pbandk.testpb.Proto3Extensions.repeatedInt32);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int NON_OPTIONAL_INT32_FIELD_NUMBER = 50000;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Integer> nonOptionalInt32 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int OPTIONAL_INT32_FIELD_NUMBER = 50001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Integer> optionalInt32 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int REPEATED_INT32_FIELD_NUMBER = 50002;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.util.List<java.lang.Integer>> repeatedInt32 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%pbandk/testpb/proto3_extensions.proto\022" +
      "\rpbandk.testpb\032 google/protobuf/descript" +
      "or.proto:;\n\022non_optional_int32\022\035.google." +
      "protobuf.FieldOptions\030\320\206\003 \001(\005::\n\016optiona" +
      "l_int32\022\035.google.protobuf.FieldOptions\030\321" +
      "\206\003 \001(\005\210\001\001:7\n\016repeated_int32\022\035.google.pro" +
      "tobuf.FieldOptions\030\322\206\003 \003(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    nonOptionalInt32.internalInit(descriptor.getExtensions().get(0));
    optionalInt32.internalInit(descriptor.getExtensions().get(1));
    repeatedInt32.internalInit(descriptor.getExtensions().get(2));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
